Repository kubevirt/cloud-image-builder, pull requests merged in 2018-10, with the labels that each got.

#60 Fix kubevirt ansible and multus issues
  build.sh
  image-files/multus-config.yml
  kubevirt-ami-centos.json
Labels: size/M

#61 Use a weave net that doesnt conflict with aws vpcs
  image-files/first-boot-centos.sh
Labels: size/XS

#63 Update motd with a statement on where to report issues.
  image-files/motd.j2
Labels: size/XS

#64 Download virtctl to image-files directory
  build.sh
  tests.yml
  tests/cirros-vm.yaml
  tests/cirros-vmi.yaml
Labels: size/M

#65 Remove CDI during first boot
  image-files/first-boot-centos.sh
Labels: size/XS

#66 Remove multus patch
  build.sh
Labels: size/XS

#68 GCP publishing fix
  gcp-image-publish.sh.j2
  gcp-image-publish.yml
Labels: size/M

#69 Rename tests directory to manifests
  manifests/cirros-pvc.yaml
  manifests/cirros-vm.yaml
  manifests/storage-setup.yaml
  tests.yml
Labels: size/S

#70 Add tests for lab2
  test-lab2.yml
  tests.yml
Labels: size/M
