Repository kubevirt/cloud-image-builder, pull requests merged in 2019-10, with the labels that each got.

#124 Updating gitignore and adding binaries
  .gitignore
  shell/build.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#126 Update TODO
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#129 Use curl and adjust spacing
  bin/.placeholder
  shell/build.sh
  shell/deploy_kubernetes.j2
  shell/first-boot.sh
  shell/publish.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#130 Fix URL in motd
  shell/first-boot.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#131 define kv version
  ansible/minikube-setup.yml
Labels: dco-signoff: yes

#132 Update README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
