Repository kubevirt/cloud-image-builder, pull requests merged in 2019-06, with the labels that each got.

#114 feat: add owners file
  OWNERS
Labels: size/S

#115 Misc updates to make the build process easier to understand
  Jenkinsfile
  build.sh
  cleanup.sh
  environment.aws
  environment.gcp
  gcp-image-publish.yml
  image-files/first-boot-centos.sh
  kubevirt-ami-centos.json
  test.sh
  test.txt
Labels: lgtm, size/M

#117 Resolve testing issue
  tests/cdi-lab.yml
Labels: lgtm, size/S
